#Connecting database
spring:
  application:
    name: bankingapp
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 9000
  servlet:
    context-path: /api


#Eureka
eureka:
  instance:
    hostname: localhost
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/